### ISSUE TITLE
Adding Rust and Julia

### ISSUE THREAD

**Issue by chyzwar** [Open-AI/Open-AI#1]
Hi

Are you willing to consider an Rust and Julia for implementation,

Did Open-AI started to work on anything? If yes It would be possible for community to start on implementation.

**Comment by AlexisTM** [comment]
Hey,

**I did not work on the project at this time**

I am on my last year and doing my thesis in a totally different field and have not much time. Therefore the project is on hold. 

I never heard about Julia, and saw Rust in [redox-os](https://github.com/redox-os/redox), I don't know why we should/should not use those, but I will add it in the choices.

I think it is better to work on the design more than the implementation, because the project is not mature enough and will change a lot over time. That being said, a simple implementation can show design errors and problems.

**Comment by chyzwar** [comment]
http://julialang.org/ interesting for scientific computation. Imo project should pick max 3 language otherwise it would be difficult to share code/expertise. Additionally project seems to be more long term, it might be better to choose something more modern and promising for implementation (rust, julia, idris, nim). 

Design would be high level anyway, but there would be for sure place for small parts that can be implemented even now and be useful for someone. Like library for deep learning with cuda/opencl back-end or some innovate algorithms. 

It is up to Open AI how you want to engage with community, you have now some publicity that you could use to attract people to project.
